### ISSUE TITLE
Terrain floats over small parts

### ISSUE THREAD

**Issue by umustbeloggedintododat** [mkargus/PartToTerrain#10]
- Part to Terrain Version: 1.4.0-1
- Roblox Studio Version: 0.487.1.426995

Steps to Reproduce:

1. Make a flat part, and put it on the ground
2. Convert it
3. The part floats

Console log:

**Comment by mkargus** [comment]
Do you have the "Delete part when converted" setting turn off and the part being unanchored?

**Comment by umustbeloggedintododat** [comment]
turned on and off both ones
and it still happens
![seoiyukjsetouk](https://user-images.githubusercontent.com/54049600/126700781-1fe87998-98fc-42e4-8b15-7816fbad5d5e.PNG)

**Comment by mkargus** [comment]
Thank you for clarifying! I thought the bug was you had converted the part without anchoring it and ran "play solo".

This bug is related to a Roblox limitation with how it handles small parts and it's not something I can't fix anytime soon unfortunately.

**Comment by umustbeloggedintododat** [comment]
oh
