### ISSUE TITLE
Mesh Support?

### ISSUE THREAD

**Issue by G-Utopia** [mkargus/PartToTerrain#11]
How about mesh support. That would make map making so better since you create a mesh in Blender and use it to convert to Terrain in Roblox. Just an idea.

**Comment by mkargus** [comment]
This is not possible to add in unfortunately. There would be too many issues on how to implement a feature like this such as:
developers not being able to access to the mesh's data without requiring a third-party webserver and having to work for at least [8 different mesh formants](https://devforum.roblox.com/t/roblox-mesh-format/326114/1) for external meshes.
